### ISSUE TITLE
De-Fork Weekender Repo from Parent

### ISSUE THREAD

**Issue by kmcleste** [dikaia-ai/weekender-blog#2]
Since the original repo (https://github.com/kmcleste/personal-blog) is no longer being maintained, we should probably detach the fork from it's parent. This way we will not constantly be reminded that this repo is X commits ahead **and** since we will never fetch any upstream changes. I also have no intention of adding posts to my original repository.

This can be done by using the GitHub virtual assistant and requesting to detach the forked repo. [Link to the assistant](https://support.github.com/request/fork?tags=fork).

**Comment by wesslen** [comment]
If I did it correctly -- big assumption -- I don't think I can b/c I'm not the owner of your repo (original repo).

![790FE406-25BA-423C-B6A0-9F425C7FFDD3](https://user-images.githubusercontent.com/7621432/164737635-bac4b9c5-2477-4d13-b459-3aabf3b07e56.png)

**Comment by kmcleste** [comment]
Okay - I reassigned this issue to me. Will complete this evening.

**Comment by kmcleste** [comment]
Fork has been detached. Treat this repo as standalone.
